In [1]:
import cryptpandas
dp1 = cryptpandas.read_encrypted(path="./release_3547.crypt", password='oUFtGMsMEEyPCCP6')
dp1

,strat_0,strat_1,strat_2,strat_3,strat_4,strat_5,strat_6,strat_7,strat_8,strat_9,...,strat_12,strat_13,strat_14,strat_15,strat_16,strat_17,strat_18,strat_19,strat_20,strat_21
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-1.216100,NaN,NaN,NaN,NaN,NaN
1,-1.045104,NaN,NaN,NaN,NaN,0.139780,1.481773,NaN,1.298774,NaN,...,NaN,NaN,NaN,-3.467195,1.344721,-0.175514,NaN,NaN,NaN,-0.827335
2,-0.229267,NaN,NaN,NaN,NaN,0.109780,0.731916,NaN,1.748748,NaN,...,NaN,NaN,NaN,-1.709005,0.681587,-0.235082,-1.271263,NaN,NaN,-0.121570
3,-0.332475,NaN,-0.056052,NaN,NaN,-0.038044,-0.557418,-0.246940,0.043789,NaN,...,NaN,NaN,NaN,0.506470,-0.403906,0.249474,-0.151417,-0.253624,NaN,-1.002791
4,-0.827446,NaN,-0.349031,NaN,NaN,-0.035166,-1.177777,-0.795178,-1.105112,NaN,...,NaN,NaN,NaN,0.370537,-0.813284,0.143559,0.391880,-0.888127,NaN,0.233682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3543,-0.381309,-0.212961,0.501306,0.322370,-0.103106,-0.557941,-0.020194,-0.008013,-0.355781,-0.881419,...,0.096630,0.679358,0.193971,-0.011222,-0.224635,-0.192642,0.206517,0.198630,0.295600,1.135041
3544,0.620255,0.064530,0.391176,-0.679921,-1.709302,1.486581,0.246001,-0.131926,0.878312,0.535155,...,-0.538533,0.895913,0.201795,0.012643,0.309842,-0.007732,-0.657715,-0.205288,-0.786703,-0.074781
3545,0.224598,0.413439,0.376754,-1.812926,-1.050624,0.827850,0.575480,-1.391991,0.693199,0.626953,...,0.822201,1.718395,-0.151103,-0.000421,0.083085,-0.103815,-0.328812,-1.100259,-0.219447,-1.173045
3546,-0.519673,-0.923652,-0.969943,-1.200744,-1.621024,-0.776032,-1.095705,0.621262,-0.606028,-1.556457,...,0.139280,-0.344232,0.560597,-0.006781,-0.723691,0.092065,0.281789,0.697799,0.301284,0.997957
3547,-0.054196,-0.073748,-0.315726,-1.033543,-0.608461,0.306113,0.490871,-0.607191,0.271265,-0.401861,...,0.590406,-0.366171,-0.426450,0.005347,0.247545,-0.701139,0.014518,-0.552265,-0.063815,-0.896698

In [5]:
dp1.head()

,strat_0,strat_1,strat_2,strat_3,strat_4,strat_5,strat_6,strat_7,strat_8,strat_9,...,strat_12,strat_13,strat_14,strat_15,strat_16,strat_17,strat_18,strat_19,strat_20,strat_21
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-1.216100,NaN,NaN,NaN,NaN,NaN
1,-1.045104,NaN,NaN,NaN,NaN,0.139780,1.481773,NaN,1.298774,NaN,...,NaN,NaN,NaN,-3.467195,1.344721,-0.175514,NaN,NaN,NaN,-0.827335
2,-0.229267,NaN,NaN,NaN,NaN,0.109780,0.731916,NaN,1.748748,NaN,...,NaN,NaN,NaN,-1.709005,0.681587,-0.235082,-1.271263,NaN,NaN,-0.121570
3,-0.332475,NaN,-0.056052,NaN,NaN,-0.038044,-0.557418,-0.246940,0.043789,NaN,...,NaN,NaN,NaN,0.506470,-0.403906,0.249474,-0.151417,-0.253624,NaN,-1.002791
4,-0.827446,NaN,-0.349031,NaN,NaN,-0.035166,-1.177777,-0.795178,-1.105112,NaN,...,NaN,NaN,NaN,0.370537,-0.813284,0.143559,0.391880,-0.888127,NaN,0.233682

In [11]:
dp1.nunique()

strat_0     3514
strat_1     3438
strat_2     3519
strat_3     3346
strat_4     3233
strat_5     3514
strat_6     3514
strat_7     3519
strat_8     3514
strat_9     3517
strat_10    3513
strat_11    3491
strat_12    3432
strat_13    3434
strat_14    3510
strat_15    3514
strat_16    3504
strat_17    3517
strat_18    3513
strat_19    3519
strat_20    3510
strat_21    3521
dtype: int64

In [17]:
dp1.shape

(3548, 22)

In [19]:
dp1.isna().sum()

strat_0       1
strat_1      83
strat_2       3
strat_3     174
strat_4      63
strat_5       1
strat_6       1
strat_7       3
strat_8       1
strat_9       5
strat_10      5
strat_11      0
strat_12     83
strat_13     83
strat_14      5
strat_15      1
strat_16      0
strat_17      1
strat_18      2
strat_19      3
strat_20      5
strat_21      1
dtype: int64

In [3]:
dp2 = cryptpandas.read_encrypted(path="./release_3611.crypt", password='GMJVDf4WWzsV1hfL')
dp2

,strat_0,strat_1,strat_2,strat_3,strat_4,strat_5,strat_6,strat_7,strat_8,strat_9,...,strat_13,strat_14,strat_15,strat_16,strat_17,strat_18,strat_19,strat_20,strat_21,strat_22
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-1.216100,NaN,NaN,NaN,NaN,NaN,NaN
1,-1.045104,NaN,NaN,NaN,NaN,0.139780,1.481773,NaN,1.298774,NaN,...,NaN,NaN,-3.467195,1.344721,-0.175514,NaN,NaN,NaN,-0.827335,NaN
2,-0.229267,NaN,NaN,NaN,NaN,0.109780,0.731916,NaN,1.748748,NaN,...,NaN,NaN,-1.709005,0.681587,-0.235082,-1.271263,NaN,NaN,-0.121570,NaN
3,-0.332475,NaN,-0.056052,NaN,NaN,-0.038044,-0.557418,-0.246940,0.043789,NaN,...,NaN,NaN,0.506470,-0.403906,0.249474,-0.151417,-0.253624,NaN,-1.002791,-0.138613
4,-0.827446,NaN,-0.349031,NaN,NaN,-0.035166,-1.177777,-0.795178,-1.105112,NaN,...,NaN,NaN,0.370537,-0.813284,0.143559,0.391880,-0.888127,NaN,0.233682,-0.819131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3607,0.000000,-0.017727,-0.056024,0.215479,0.000000,0.000000,0.000000,0.051509,0.000000,-0.011121,...,-0.087883,0.000000,0.000000,0.000000,0.205559,0.000000,0.052861,0.000000,0.000805,0.000000
3608,-0.352538,0.924958,-0.543399,1.443084,0.877140,0.026766,-0.164681,-0.613593,0.210850,-0.738736,...,-0.223523,0.250423,-0.161238,0.107656,0.384633,-0.270106,-0.433995,-0.314531,0.534567,0.279055
3609,1.298432,-0.796700,0.398380,0.321661,2.292223,0.004396,-3.962713,0.646088,-1.151465,-0.297246,...,-0.266560,-0.083415,1.632093,-0.288840,-0.098182,1.092993,0.387624,1.494475,-0.091302,-1.196047
3610,-0.969457,-0.585751,0.733022,-1.581433,-0.802236,-0.609019,2.711338,1.587876,0.072545,1.358958,...,-0.165569,2.045311,0.323374,1.026497,-0.249033,-0.201358,1.299989,-0.197355,-0.998485,1.439076
3611,0.035245,-1.507826,-1.678676,-0.965109,-0.457449,0.207018,-0.784508,1.090475,0.320508,-1.593540,...,0.086925,-1.377536,-0.758486,-0.860501,-0.383984,-0.112228,1.821161,-0.130143,-0.293695,-0.414882